param([Parameter(Mandatory=$true)][string]$RepoRoot,[Parameter(Mandatory=$true)][string]$TargetDir,[string]$GoldenManifest,[string]$CurrentManifest)
$ErrorActionPreference='Stop'
if(!$GoldenManifest){$GoldenManifest=Join-Path $RepoRoot 'docs\baselines\1.26.2.1-BAT.sha256'}
if(!$CurrentManifest){$CurrentManifest=Join-Path $RepoRoot 'config\build\current-resource-manifest.sha256'}
function Read-Manifest($path,$required){
 if(!(Test-Path -LiteralPath $path)){if($required){throw "manifest missing: $path"}else{return @()}}
 $out=@{}; foreach($line in (Get-Content -LiteralPath $path)) { if($line -match '^\s*(#|$)'){continue}; $x=$line -split '\s+',3; if($x.Count -ne 2 -or $x[0] -notmatch '^[0-9A-Fa-f]{64}$'){throw "invalid manifest line: $line"}; $rel=$x[1].TrimStart('*') -replace '/','\'; if([IO.Path]::IsPathRooted($rel) -or $rel -match '(^|\\)\.\.(\\|$)'){throw "unsafe path: $rel"}; $full=[IO.Path]::GetFullPath((Join-Path $RepoRoot $rel)); if(!$full.StartsWith([IO.Path]::GetFullPath($RepoRoot),[StringComparison]::OrdinalIgnoreCase)){throw "path escape: $rel"}; if($out.ContainsKey($rel)){throw "duplicate path: $rel"}; $out[$rel]=$x[0].ToUpperInvariant() }; if($required -and !$out.Count){throw 'manifest empty'}; return $out
}
$gold=Read-Manifest $GoldenManifest $true; $cur=Read-Manifest $CurrentManifest $true
$all=@{}; foreach($k in $gold.Keys){if($k -like 'swf\*'){$all[$k]=@($gold[$k],'golden baseline')}}; foreach($k in $cur.Keys){if($k -like 'swf\*'){$all[$k]=@($cur[$k],'current manifest')}}
$stage="$TargetDir.__stage"; if(Test-Path $stage){Remove-Item $stage -Recurse -Force}; New-Item $stage -ItemType Directory -Force|Out-Null
try { foreach($rel in $all.Keys){$src=Join-Path $RepoRoot $rel; if(!(Test-Path $src)){ $src=Join-Path (Join-Path $RepoRoot 'swf') ([IO.Path]::GetFileName($rel)) }; if(!(Test-Path $src)){throw "missing resource: $rel"}; $h=(Get-FileHash $src -Algorithm SHA256).Hash; if($h -ine $all[$rel][0]){throw "hash mismatch: $rel"}; Write-Output "[CHECK] $rel ($($all[$rel][1]))"; $dst=Join-Path $stage ([IO.Path]::GetFileName($rel)); Copy-Item $src $dst; if((Get-FileHash $dst -Algorithm SHA256).Hash -ine $h){throw "copy hash mismatch: $rel"} }; if(Test-Path $TargetDir){Get-ChildItem $TargetDir -Force|Remove-Item -Recurse -Force}; New-Item $TargetDir -ItemType Directory -Force|Out-Null; Get-ChildItem $stage -Force|Move-Item -Destination $TargetDir; Remove-Item $stage -Recurse -Force; Write-Output "[OK] Runtime resources prepared: $($all.Count)" } catch { if(Test-Path $stage){Remove-Item $stage -Recurse -Force}; Write-Error $_; exit 1 }
